version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # This is annoying, but node-sass needs to be rebuilt
      - run: npm rebuild node-sass --force
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn build:example
